print("Dime 4 valores en el siguiente orden: número entero, número decimal, un booleano y una cadena de caracteres")
entero = int(input())
decimal = float(input())
booleano = bool(input())
cadena = input()
print(entero ,"es", type(entero))
print(decimal ,"es", type(decimal))
print(booleano ,"es", type(booleano))
print(cadena ,"es", type(cadena))